[project]
name = "rio-faux"
description = "Create empty image from a model."
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
authors = [
    {name = "Vincent Sarago", email = "vincent@developmentseed.com"},
]
keywords = ["rasterio"]
classifiers = [
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: GIS",
]
dynamic = ["version"]
dependencies = [
    "click>=7.0",
    "rasterio>=1.1",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
]
dev = [
    "pre-commit",
]
docs = [
    "mkdocs",
    "mkdocs-material",
]

[project.urls]
Source = "https://github.com/cogeotiff/rio-faux"
Documentation = "https://cogeotiff.github.io/rio-faux/"

[project.entry-points."rasterio.rio_plugins"]
cogeo = "rio_faux.cli:faux"

[build-system]
requires = ["flit>=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "rio_faux"

[tool.flit.sdist]
exclude = [
    "tests/",
    "docs/",
    ".github/",
    "CHANGES.md",
    "codecov.yml",
    "CONTRIBUTING.md",
    "mkdocs.yml",
]

[tool.isort]
profile = "black"
known_first_party = ["rio_fake"]
known_third_party = ["rasterio", "click"]
default_section = "THIRDPARTY"

[tool.mypy]
no_strict_optional = "True"
ignore_missing_imports = "True"

[tool.pydocstyle]
select = "D1"
match = "(?!test).*.py"
